# -*- coding: utf-8 -*-
"""python kafka_producer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NPTHl4RaoSDIotuqYwfcVYq0Ol89B9p9
"""

import os
import requests
import tarfile
import shutil

pip install confluent_kafka

kafka_url = "https://downloads.apache.org/kafka/3.7.0/kafka_2.13-3.7.0.tgz"
response = requests.get(kafka_url, stream=True)

with open("kafka_2.13-3.7.0.tgz", "wb") as file:
    for chunk in response.iter_content(chunk_size=8192):
        file.write(chunk)

print("Kafka downloaded successfully!")

with tarfile.open("kafka_2.13-3.7.0.tgz", "r:gz") as tar:
    tar.extractall()

print("Kafka extracted successfully!")

source_dir = os.path.join(os.getcwd(), "kafka_2.13-3.7.0")
destination_dir = "C:\\kafka"

if os.path.exists(destination_dir):
    shutil.rmtree(destination_dir)

shutil.move(source_dir, destination_dir)
print(f"Kafka moved to {destination_dir} successfully!")

kafka_server_config_path = os.path.join(destination_dir, "config", "server.properties")
zookeeper_config_path = os.path.join(destination_dir, "config", "zookeeper.properties")

def update_config(file_path, updates):
    with open(file_path, "r") as file:
        lines = file.readlines()

    with open(file_path, "w") as file:
        for line in lines:
            for key, value in updates.items():
                if line.startswith(key):
                    line = f"{key}={value}\n"
            file.write(line)

kafka_server_updates = {
    "log.dirs": "C:\\kafka\\logs",
    "zookeeper.connect": "localhost:2181"
}
update_config(kafka_server_config_path, kafka_server_updates)

zookeeper_updates = {
    "dataDir": "C:\\kafka\\zookeeper_data"
}
update_config(zookeeper_config_path, zookeeper_updates)

print("Kafka server and Zookeeper configurations updated successfully!")

batch_file_content = """@echo off
cd C:\\kafka
call .\\bin\\windows\\zookeeper-server-start.bat .\\config\\zookeeper.properties
"""
batch_file_path = os.path.join(destination_dir, "start_zookeeper.bat")

with open(batch_file_path, "w") as file:
    file.write(batch_file_content)

print(f"Zookeeper start batch file created at {batch_file_path}")

print("To start Zookeeper, navigate to the Kafka folder and run the 'start_zookeeper.bat' file.")



